services:
  # Backend API
  - type: web
    name: misk-diploma-backend
    runtime: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    
  # Frontend
  - type: web
    name: misk-diploma-frontend
    runtime: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://misk-diploma-backend.onrender.com/api/v1